version: '3.8'

services:
  spell-binder:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        PB_VERSION: ${PB_VERSION:-0.19.4}
    image: spell-binder:${IMAGE_TAG:-latest}
    container_name: ${CONTAINER_NAME:-spell-binder-prod}
    ports:
      - "${HOST_PORT:-80}:8080"
    volumes:
      - pb_data:/pb/pb_data
      - ${BACKUP_DIR:-./backups}:/backups:ro
      - ${LOG_DIR:-./logs}:/logs
    environment:
      - PB_ENCRYPTION_KEY=${PB_ENCRYPTION_KEY}
      - PB_ADMIN_EMAIL=${PB_ADMIN_EMAIL:-}
      - PB_ADMIN_PASSWORD=${PB_ADMIN_PASSWORD:-}
      - PB_HTTP_ADDR=0.0.0.0:8080
      - TZ=${TIMEZONE:-UTC}
    restart: always
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "--timeout=5", "http://localhost:8080/api/health"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    labels:
      - "com.docker.compose.project=spell-binder"
      - "environment=production"
      - "maintainer=spell-binder"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'

  # Optional: Reverse proxy with SSL termination
  nginx:
    image: nginx:alpine
    container_name: ${NGINX_CONTAINER_NAME:-spell-binder-nginx}
    ports:
      - "${HTTPS_PORT:-443}:443"
      - "${HTTP_PORT:-80}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ${LOG_DIR:-./logs}/nginx:/var/log/nginx
    depends_on:
      - spell-binder
    restart: always
    profiles:
      - nginx
    labels:
      - "com.docker.compose.project=spell-binder"
      - "environment=production"
      - "service=reverse-proxy"

volumes:
  pb_data:
    driver: local
    labels:
      - "com.docker.compose.project=spell-binder"
      - "environment=production"

networks:
  default:
    name: spell-binder-network
    labels:
      - "com.docker.compose.project=spell-binder"